chore: migrate to new user preferences store
Pocket/recommendation-api pull request #1060
Opened 2023-08-08 23:47 UTC by mmiermans

# Goal
Cleanup code by only reading/writing recommendation preferences based on hashed_user_id.

# Context
We’ve been double-writing recommendation (topic) preferences to two stores keyed on user_id and hashed_user_id since August 2022. The latter is the recommended identifier for users. Last year we also did a data migration from the old to the new store.

We also did a data migration in 2022 from the old to the new store. The Athena tables have an almost identical number of distinct user ids. The difference is small enough that I don't think it warrants further investigation.

|                | **unique user count** |
|:--------------:|:---------------------:|
|     **old**    | 557953                |
|     **new**    | 557568                |
| **difference** | 385 (0.07%)                   |

## Review
- [ ] Security @ReviewerA
- [ ] Test coverage @ReviewerC
- [ ] ...

Have you followed the guidelines in our Contributing document?

## Deployment
- [ ] Merge and deploy change
- [ ] Delete old Feature Group

## Reference

Tickets:
* https://mozilla-hub.atlassian.net/browse/MC-26

## Implementation Decisions
- I kept 'V2' in the class name to make the history easier to read.

2023-08-10 20:35 UTC, jeshuaborges approved these changes
Nice work. This all looks super straight forward to me. My only feedback would be to rename everything that ended up with a 'v2' suffix to remove the suffix.

2023-08-10 20:35 UTC, jeshuaborges commented on app/graphql/resolvers/corpus_slate_lineup_resolvers.py
> +            preferences_provider=UserRecommendationPreferencesProviderV2(di.aioboto3_session, topic_provider),
Should we rename `UserRecommendationPreferencesProviderV2` to `UserRecommendationPreferencesProvider` as future devs may not care, or know about the version history?

2023-08-10 20:35 UTC, jeshuaborges commented on app/graphql/resolvers/user_recommendation_preferences_resolvers.py
> +    await preferences_provider_v2.put(model_v2)
Same comment about the _v2 stuff here.

2023-08-10 20:35 UTC, jeshuaborges commented on app/graphql/resolvers/user_recommendation_preferences_resolvers.py
> +    await preferences_provider_v2.put(model_v2)
Also nice work reducing to a single path.

2023-08-10 21:14 UTC, jsrawan-mobo requested changes
When I searched for 'user.user_id' i found following files with references that I don't see in the PR

app/data_providers/snowplow/entities.py
app/data_providers/snowplow/subject.py

2023-08-10 22:42 UTC, mmiermans commented
@jsrawan-mobo Those references to user.user_id are unrelated to storing user preferences, and don't need to be changed/removed.

2023-08-10 23:10 UTC, jsrawan-mobo approved these changes

2023-08-10 23:12 UTC, jsrawan-mobo commented
> Thanks for searching through the repo, though! I always try to do the same with removal PRs.

I did see that the 'user_id' field wasn't removed so I suppose its still used for analytics.

Just to clarify - if you delete the 'old' feature group in Athena, then how does 'user_id' get populated in the RequestUser?

2023-08-11 15:48 UTC, mmiermans commented
> Just to clarify - if you delete the 'old' feature group in Athena, then how does 'user_id' get populated in the RequestUser?

@jsrawan-mobo For logged-in users, we receive `user_id` as a header from Apollo. A list of all headers is at the bottom of the [Pocket Graph readme page in Apollo Studio](https://studio.apollographql.com/graph/pocket-client-api/variant/current/home).

2023-08-11 17:35 UTC, merged