Check that GUIDs are unique
Pocket/recommendation-api pull request #209
Opened 2021-03-05 19:14 UTC by iwsmith

Check configs to make sure GUIDs used by Slates and SlateLineups are unique.

2021-03-08 16:27 UTC, chelseatroy commented on tests/functional/json/slate_lineup_config.py
> +        raise ValueError(f"GUID is reused for slate and lineup: {guid_overlap}")
There are faster ways to do this, but they either require an extra step to get the actual duplicated ID or aren't as clear to follow as this, so I'm happy with this solution.

2021-03-08 16:31 UTC, chelseatroy requested changes
The solution I'm happy with. I think it needs three automated tests:

- one for duped slate ids
- one for duped layout ids
- one for reused slate ids among the layout ids

2021-03-08 16:32 UTC, jpetto approved these changes
looks solid to me 🙌

2021-03-08 17:02 UTC, kkyeboah reviewed
This works for me but deferring to @chelseatroy for the requested changes.

2021-03-08 18:27 UTC, iwsmith commented
> The solution I'm happy with. I think it needs three automated tests:
> 
>     * one for duped slate ids
> 
>     * one for duped layout ids
> 
>     * one for reused slate ids among the layout ids
> 
> 
> Happy to pair on that if that's helpful!

Hmm, I've never written a test for a test before. I think this really indicates this code shouldn't be in a unit test, but instead somewhere else. I will move stuff around and resubmit.

2021-03-09 16:49 UTC, chelseatroy approved these changes
That's the stuff!

2021-03-09 20:52 UTC, merged