Add required_terraform pinning Terraform to 0.13.5
Pocket/recommendation-api pull request #333
Opened 2021-08-06 13:22 UTC by danieldreier

# Goal

Terraform operations should error out if Terraform is run with newer Terraform versions.

## Todos
- [ ] needs to be run / tested

## Reference
@bassrock, @kkyeboah and I discussed this in slack

I tested this in a toy environment but haven't run the `recommendation-api` CDKTF codebase locally

2021-08-16 16:09 UTC, mmiermans approved these changes
lgtm :+1: Thanks for help fix this!

I'll look to @kkyeboah for a second review.

2021-08-20 01:18 UTC, kkyeboah requested changes
Thank you for your contribution 💯. We definitely need to require the version.

I do have a small suggestion to fix your addition.

2021-08-20 01:18 UTC, kkyeboah commented on .aws/src/main.ts
> +stack.addOverride("terraform.required_version", "0.13.5")
```suggestion
const stack = new RecommendationAPI(app, 'recommendation-api');
stack.addOverride("terraform.required_version", "0.13.5")
```

2022-08-18 15:36 UTC, mmiermans commented
We've since migrated to Terraform 1.0.11. Not sure if pinning is still necessary.

2022-08-18 15:36 UTC, closed without merging